ARG TAG
FROM nvcr.io/nvidia/l4t-jetpack:${TAG}

RUN apt-get update && \
    apt-get install -y python3-pip

RUN pip3 install -U pip && \
    pip3 install matplotlib pillow numpy pandas

RUN pip3 install jupyterlab && \
    jupyter lab --generate-config && \
    rm ~/.jupyter/jupyter_lab_config.py

COPY jupyter_lab_config.py ~/.jupyter/

WORKDIR /workspace
CMD ["/bin/bash"]