FROM nvcr.io/nvidia/l4t-pytorch:r35.1.0-pth1.13-py3

RUN pip3 install -U pip && \
    pip3 install -y matplotlib pillow numpy pandas

RUN pip3 install -yjupyterlab && \
    jupyter lab --generate-config && \
    rm ~/.jupyter/jupyter_lab_config.py

COPY ./jupyter_lab_config.py ~/.jupyter/jupyter_lab_config.py

WORKDIR /workspace
CMD ["/bin/bash"]